/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of Faster.xs. Do not edit this file, edit Faster.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Faster.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <bloom.h>
#include "const-c.inc"
typedef bloom Bloomer;

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 23 "Faster.c"

/* INCLUDE:  Including 'const-xs.inc' from 'Faster.xs' */


XS(XS_Bloom__Faster_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::constant", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	IV		iv;
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 53 "Faster.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "const-xs.inc"
        /* Change this to constant(aTHX_ s, len, &iv, &nv);
           if you need to return both NVs and IVs */
	type = constant(aTHX_ s, len, &iv);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid Bloom macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Bloom macro %s, used",
				   s));
          PUSHs(sv);
          break;
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break;
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Bloom macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 130 "Faster.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'Faster.xs' from 'const-xs.inc' */


XS(XS_Bloom__Faster_binit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_binit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::binit", "size, hashes, capacity, error_rate");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	unsigned long	size = (unsigned long)SvUV(ST(0));
	int	hashes = (int)SvIV(ST(1));
	unsigned long	capacity = (unsigned long)SvUV(ST(2));
	float	error_rate = (float)SvNV(ST(3));
#line 20 "Faster.xs"
	bloom *newbloom;
#line 158 "Faster.c"
	Bloomer *	RETVAL;
#line 22 "Faster.xs"
	if ((newbloom = (bloom *)malloc(sizeof(bloom))) == NULL) {
		perror("malloc");
	}
	if (bloom_init(newbloom,size,capacity,error_rate,hashes,NULL,0) != 0) {
		RETVAL = NULL;
	} else {
		RETVAL = newbloom;
	}
#line 169 "Faster.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "BloomerPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bloom__Faster_binit_sugg); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_binit_sugg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::binit_sugg", "n, e");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	n = (char *)SvPV_nolen(ST(0));
	char *	e = (char *)SvPV_nolen(ST(1));
#line 39 "Faster.xs"
	bloom *newbloom;
#line 193 "Faster.c"
	Bloomer *	RETVAL;
#line 41 "Faster.xs"
	struct bloomstat stat;
	unsigned long real_n = atoll(n);
	double real_e = atof(e);

	get_suggestion(&stat,real_n,real_e);
	if ((newbloom = (bloom *)malloc(sizeof(bloom))) == NULL) {
		perror("malloc");
	}
	if (bloom_init(newbloom,stat.elements,real_n,real_e,stat.ideal_hashes,NULL,1) != 0) {
		RETVAL = NULL;
	} else {
		RETVAL = newbloom;
	}
#line 209 "Faster.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "BloomerPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bloom__Faster_suggestion); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_suggestion)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::suggestion", "n, e, m, k");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	n = (char *)SvPV_nolen(ST(0));
	char *	e = (char *)SvPV_nolen(ST(1));
	SV *	m = ST(2);
	int	k = (int)SvIV(ST(3));
#line 66 "Faster.xs"
	char holder[1000];
	struct bloomstat stat;
	unsigned long real_n = atoll(n);
	double real_e = atof(e);

	get_suggestion(&stat,real_n,real_e);

	sprintf(holder,"%lld",stat.elements);
	m = newSVpvn(holder,strlen(holder));
	k = stat.ideal_hashes;
#line 244 "Faster.c"
	ST(2) = m;
	SvSETMAGIC(ST(2));
	sv_setiv(ST(3), (IV)k);
	SvSETMAGIC(ST(3));
    }
    XSRETURN_EMPTY;
}


XS(XS_Bloom__Faster_bloom_destroyer); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_bloom_destroyer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::bloom_destroyer", "newbloom");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Bloomer *	newbloom;
#line 84 "Faster.xs"
	bloom *thisbloom;
#line 269 "Faster.c"

	if (sv_derived_from(ST(0), "BloomerPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    newbloom = INT2PTR(Bloomer *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bloom::Faster::bloom_destroyer",
			"newbloom", "BloomerPtr");
#line 86 "Faster.xs"
	thisbloom = (bloom *)newbloom;
	bloom_destroy(thisbloom);
	free(thisbloom);
#line 283 "Faster.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Bloom__Faster_bcapacity); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_bcapacity)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::bcapacity", "newbloom");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Bloomer *	newbloom;
#line 94 "Faster.xs"
	bloom *thisbloom;
#line 304 "Faster.c"
	long	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "BloomerPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    newbloom = INT2PTR(Bloomer *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bloom::Faster::bcapacity",
			"newbloom", "BloomerPtr");
#line 96 "Faster.xs"
	thisbloom = (bloom *)newbloom;
	RETVAL=thisbloom->stat.capacity;
#line 319 "Faster.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bloom__Faster_berror_rate); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_berror_rate)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::berror_rate", "newbloom");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Bloomer *	newbloom;
#line 105 "Faster.xs"
	bloom *thisbloom;
#line 341 "Faster.c"
	long	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "BloomerPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    newbloom = INT2PTR(Bloomer *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bloom::Faster::berror_rate",
			"newbloom", "BloomerPtr");
#line 107 "Faster.xs"
	thisbloom = (bloom *)newbloom;
	RETVAL=thisbloom->stat.e;
#line 356 "Faster.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bloom__Faster_belements); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_belements)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::belements", "newbloom");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Bloomer *	newbloom;
#line 116 "Faster.xs"
	bloom *thisbloom;
#line 378 "Faster.c"
	long	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "BloomerPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    newbloom = INT2PTR(Bloomer *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bloom::Faster::belements",
			"newbloom", "BloomerPtr");
#line 118 "Faster.xs"
	thisbloom = (bloom *)newbloom;
	RETVAL=thisbloom->stat.elements;
#line 393 "Faster.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bloom__Faster_bhash_functions); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_bhash_functions)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::bhash_functions", "newbloom");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Bloomer *	newbloom;
#line 127 "Faster.xs"
	bloom *thisbloom;
#line 415 "Faster.c"
	long	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "BloomerPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    newbloom = INT2PTR(Bloomer *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bloom::Faster::bhash_functions",
			"newbloom", "BloomerPtr");
#line 129 "Faster.xs"
	thisbloom = (bloom *)newbloom;
	RETVAL=thisbloom->stat.ideal_hashes;
#line 430 "Faster.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bloom__Faster_binserts); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_binserts)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::binserts", "newbloom");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Bloomer *	newbloom;
#line 139 "Faster.xs"
	bloom *thisbloom;
#line 452 "Faster.c"
	long	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "BloomerPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    newbloom = INT2PTR(Bloomer *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bloom::Faster::binserts",
			"newbloom", "BloomerPtr");
#line 141 "Faster.xs"
	thisbloom = (bloom *)newbloom;
	RETVAL = thisbloom->inserts;
#line 467 "Faster.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bloom__Faster_test_bloom); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_test_bloom)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::test_bloom", "newbloom, str, mode");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Bloomer *	newbloom;
	char *	str = (char *)SvPV_nolen(ST(1));
	int	mode = (int)SvIV(ST(2));
#line 152 "Faster.xs"
	bloom *thisbloom;
#line 491 "Faster.c"
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "BloomerPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    newbloom = INT2PTR(Bloomer *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bloom::Faster::test_bloom",
			"newbloom", "BloomerPtr");
#line 154 "Faster.xs"
	thisbloom  = (bloom *)newbloom;
	if (mode == 1) {
		RETVAL = bloom_add(thisbloom,str);
	} else {
		RETVAL = bloom_check(thisbloom,str);
	}
#line 510 "Faster.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bloom__Faster_bserialize); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_bserialize)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::bserialize", "newbloom, fname");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Bloomer *	newbloom;
	char *	fname = (char *)SvPV_nolen(ST(1));
#line 168 "Faster.xs"
	bloom *thisbloom;
#line 533 "Faster.c"
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "BloomerPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    newbloom = INT2PTR(Bloomer *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bloom::Faster::bserialize",
			"newbloom", "BloomerPtr");
#line 170 "Faster.xs"
	thisbloom  = (bloom *)newbloom;
	if (bloom_serialize(thisbloom,fname) == 0) {
		RETVAL=1;
	} else {
		RETVAL=0;
	}
#line 552 "Faster.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bloom__Faster_bdeserialize); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_bdeserialize)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::bdeserialize", "fname");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	fname = (char *)SvPV_nolen(ST(0));
#line 183 "Faster.xs"
	bloom *newbloom;
#line 574 "Faster.c"
	Bloomer *	RETVAL;
#line 185 "Faster.xs"
	newbloom=bloom_deserialize(fname);
	RETVAL=newbloom;
#line 579 "Faster.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "BloomerPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bloom__Faster_get_vector); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bloom__Faster_get_vector)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Bloom::Faster::get_vector", "newbloom");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Bloomer *	newbloom;
#line 195 "Faster.xs"
		char *other;
#line 602 "Faster.c"
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "BloomerPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    newbloom = INT2PTR(Bloomer *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bloom::Faster::get_vector",
			"newbloom", "BloomerPtr");
#line 197 "Faster.xs"
		if ((other = (char *)malloc(sizeof(char) * ((newbloom->stat.elements/8) + 1))) == NULL) {
			perror("malloc");
		}
		strncpy(other,newbloom->vector,(newbloom->stat.elements/8) + 1);
		RETVAL=other;
#line 620 "Faster.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Bloom__Faster); /* prototype to pass -Wmissing-prototypes */
XS(boot_Bloom__Faster)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Bloom::Faster::constant", XS_Bloom__Faster_constant, file);
        newXS("Bloom::Faster::binit", XS_Bloom__Faster_binit, file);
        newXS("Bloom::Faster::binit_sugg", XS_Bloom__Faster_binit_sugg, file);
        newXSproto("Bloom::Faster::suggestion", XS_Bloom__Faster_suggestion, file, "$$");
        newXS("Bloom::Faster::bloom_destroyer", XS_Bloom__Faster_bloom_destroyer, file);
        newXS("Bloom::Faster::bcapacity", XS_Bloom__Faster_bcapacity, file);
        newXS("Bloom::Faster::berror_rate", XS_Bloom__Faster_berror_rate, file);
        newXS("Bloom::Faster::belements", XS_Bloom__Faster_belements, file);
        newXS("Bloom::Faster::bhash_functions", XS_Bloom__Faster_bhash_functions, file);
        newXS("Bloom::Faster::binserts", XS_Bloom__Faster_binserts, file);
        newXS("Bloom::Faster::test_bloom", XS_Bloom__Faster_test_bloom, file);
        newXS("Bloom::Faster::bserialize", XS_Bloom__Faster_bserialize, file);
        newXS("Bloom::Faster::bdeserialize", XS_Bloom__Faster_bdeserialize, file);
        newXS("Bloom::Faster::get_vector", XS_Bloom__Faster_get_vector, file);
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

